obj-$(CONFIG_MXC_IPU_V3) = mxc_ipu.o
CFLAGS_ipu_common.o := -DDEBUG
CFLAGS_ipu_ic.o := -DDEBUG
CFLAGS_ipu_disp.o := -DDEBUG
CFLAGS_ipu_capture.o := -DDEBUG
CFLAGS_ipu_device.o := -DDEBUG
CFLAGS_ipu_calc_stripes_sizes.o := -DDEBUG
CFLAGS_vdoa.o := -DDEBUG
mxc_ipu-objs := ipu_common.o ipu_ic.o ipu_disp.o ipu_capture.o ipu_device.o ipu_calc_stripes_sizes.o vdoa.o

