CFLAGS_mxc_ipu.o := -DDEBUG
obj-$(CONFIG_MXC_IPU_V1) = mxc_ipu.o

CFLAGS_ipu_common.o := -DDEBUG
CFLAGS_ipu_sdc.o := -DDEBUG
CFLAGS_ipu_adc.o := -DDEBUG
CFLAGS_ipu_ic.o := -DDEBUG
CFLAGS_ipu_csi.o := -DDEBUG
CFLAGS_ipu_device.o := -DDEBUG
CFLAGS_ipu_calc_stripes_sizes.o := -DDEBUG
mxc_ipu-objs := ipu_common.o ipu_sdc.o ipu_adc.o ipu_ic.o ipu_csi.o ipu_device.o ipu_calc_stripes_sizes.o

obj-$(CONFIG_MXC_IPU_PF)        +=   pf/
